name: Skill End-to-End Tests (ovoscope)

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  ovoscope:
    uses: OpenVoiceOS/gh-automations/.github/workflows/ovoscope.yml@feat/ovoscope-intent-cache
    secrets: inherit
    with:
      python_version: '3.11'
      gh_automations_ref: 'feat/ovoscope-intent-cache'
      install_extras: 'test'
      test_path: 'test/end2end/'
      require_padatious: true
      system_deps: 'swig libfann-dev'
      pytest_workers: '0'
