name: Release Alpha and Propose Stable

on:
  pull_request:
    types: [closed]
    branches: [dev]
  workflow_dispatch:

jobs:

  publish_alpha:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'version.py'
      update_changelog: true
      publish_prerelease: true
      propose_release: true
      publish_pypi: true
      notify_matrix: true
      changelog_max_issues: 100

